---
name: Tests
run-name: ${{ github.actor }} is running test suites

on:
  push:
    branches:
      - '**'

env:
  KUBECONFORM_VERSION: "v0.7.0" # Workflow level
  ARCH: "amd64"

jobs:

  e2e-tests:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v5.0.0

      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0
        with:
          cluster_name: nxs-universal-chart-e2e
          config: tests/e2e/kind.yaml
          node_image: kindest/node:v1.35.0
          kubectl_version: v1.35.0
          wait: 60s

      - name: Run end-to-end install checks
        env:
          USE_EXISTING_CLUSTER: "true"
          CLUSTER_NAME: nxs-universal-chart-e2e
        run: bash tests/e2e/test-e2e.sh
