---
name: Tests
run-name: ${{ github.actor }} is running test suites

on:
  push:
    branches:
      - '**'

env:
  KUBECONFORM_VERSION: "v0.7.0" # Workflow level
  ARCH: "amd64"

jobs:

  smoke-tests:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v5.0.0

      - name: Update helm dependencies
        run: |
          helm dependency update

      - uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.13'
      - run: pip install PyYAML

      - name: Install kubeconform
        run: |
          curl -fsSL "https://github.com/yannh/kubeconform/releases/download/${KUBECONFORM_VERSION}/kubeconform-linux-${ARCH}.tar.gz" |
          tar -xz -C /usr/local/bin kubeconform

      - name: Run chart-testing (smoke-tests)
        run: |
          python3 tests/smokes/run/smoke.py
          --scenario default-empty
          --scenario schema-invalid-list-contract
          --scenario rendering-contract
          --scenario example-render
          --scenario example-kubeconform
